smartthings:
  ssl:
    verify: false
    ca_cert: "./certs/KDONE_SSL_CERT.crt"
    timeout: 10

power:
  controller: smartthings
  device: main_plug

aging:
  max_count: 100000
  power_off_delay_sec: 10
  boot_wait_sec: 0
  interval_sec: 15
  stop_on_fail: true

serial:
  port: "/dev/ttyUSB0"
  baudrate: 115200
  timeout_sec: 1

emmc:
  device_node: "mmcblk2"
  test_size_mb: 128
  boot_timeout_sec: 180

ilitek:
  boot_timeout_sec: 90

  fail_patterns:
    - "GET_PTL_VER"
    - "unrecognized protocol ver"
    - "api_update_ts_info failed"
    - "driver initialize failed"
    - "failed to execute cmd"
    - "GET_PTL_VER err"

  pass_patterns:
    - "ILITEK"
    - "input:"

report:
  save_dir: reports